### ISSUE TITLE
Bug ? `circuit_builder` timing | features misconfiguration  

### ISSUE THREAD

**Issue by NikitaMasych** [0xPolygonZero/plonky2#1639]
Hey guys!

In `plonky2/src/plonk/circuit_builder.rs` there is enabled import then feature `timing` is activated:

```rust
#[cfg(feature = "timing")]
use web_time::Instant;
```

after that, there is something following:

```rust
#[cfg(feature = "std")]
let start = Instant::now();
```

This breaks compilation, if try to add plonky2 with only `std` feature:

```toml
[dependencies]
plonky2 = { version = "1.0.0", default-features = false, features = ["std"] }
``` 

since rust can't find `Instant` type (being unimported because I didn't enable `timing`)

I guess at the second code snippet shall be conditional for `timing` and not `std`, like:

```rust
#[cfg(feature = "timing")]
let start = Instant::now();
```

or maybe conditional import from std, if `timing` is disabled
